### ISSUE TITLE
Is it possible to record network traffic with fpgo?

### ISSUE THREAD

**Issue by Doca** [app-fast/fpgo#1]
Great project! Thanks for making this public! I just have a question as a noob in devops etc. Would it be possible to record the network traffic (like which javascript files are loaded, images etc.) with this proxy or is it a different layer?
I use it with the --proxy-server with chromium. 

Thanks
Do

**Comment by joeky888** [comment]
Unfortunately no. HTTPS creates a secure tunnel to prevent you doing such thing. The only thing you can record is the domain name and nothing else (Not even the request route).

```
You -> secure tunnel -> http proxy -> secure tunnel -> Server
``` 

<img width="665" alt="Screenshot 2023-05-18 at 7 30 15 PM" src="https://github.com/joeky888/fpgo/assets/6928939/8bdd25e6-9b21-4888-b71c-6bd89b17ec25">

**Comment by Doca** [comment]
thanks a lot!
